### ISSUE TITLE
/dev/loop14: failed to set up loop device: No such file or directory

### ISSUE THREAD

**Issue by Byteeeeeeee** [rainestorme/murkmod#102]
**Describe the bug**
While installing I get this error along with the following line: "losetup
-P $loop" "$bin"" command failed with exit code 1.

**To Reproduce**
1. I just installed it, it worked on a different chromebook though so idk

**Expected behavior**
it to be installed

**Screenshots**
its after the losetup: /dev/FINDING FREE!!!

**System (please complete the following information):**
 - Board dedede
 - Version i've tried every version
- Installation method used idk what this means i just used vt2

**Additional context**

**Comment by Eboi47** [comment]
When you say you tried every version, did you reboot in between attempts, that could be part of the issue. It would also help if you provided a screenshot of the terminal output when the error occurs.

**Comment by Packjackisback** [comment]
Same issue here, currently debugging. If the issue isn't rebooting, it should close the loop device before exiting on error.
