### ISSUE TITLE
Murkmod does not unblock developer mode

### ISSUE THREAD

**Issue by kingofnetflix** [rainestorme/murkmod#105]
**Describe the bug**
A clear and concise description of what the bug is:

Murkmod does not unblock developer mode from system policies. 

**To Reproduce**
1. Go to **ChromeOS v130**
2. Run murkmod, latest version with custom bootsplash
3. Reboot (it hangs on startup when the script reboots) and allow it to activate developer mode (5 minute wait)
4. Once enrolled, reboot

**Expected behavior**
You should not see the policy block of developer mode. Instead, it tells you that Developer Mode is blocked by policy.

**Screenshots**
If applicable, add screenshots or videos of the problem to help explain your situation.

**System (please complete the following information):**
 - Board: Octopus (FLEEX)
 - Version: v130
- Installation method used: Developer Mode Installer [bash <(curl https://bit.ly/murkmod) on a fresh recovery]

**Additional context**
¯\_(ツ)_/¯

**Comment by rainestorme** [comment]
As it says in the README and installation guide, you need to unblock devmode in some way (likely by setting your GBB flags) before running the installer.

**Comment by Eboi47** [comment]
Why specifically do you have to have the custom bootsplash during install?

**Comment by rainestorme** [comment]
> Why specifically do you have to have the custom bootsplash during install?

You don't *have* to have the custom bootsplash during install. You can disable it in both the fakemurk > murkmod installer and the devmode installer, and you can disable it by passing `image_patcher.sh` a flag.
