### ISSUE TITLE
Murkmod directory not created in the stateful partition 

### ISSUE THREAD

**Issue by Packjackisback** [rainestorme/murkmod#107]
![image](https://github.com/user-attachments/assets/80853564-1534-43eb-912d-0d4be11a5383)
Obviously this breaks packages. Not sure what could have happened.

**Comment by rainestorme** [comment]
Have you tried `ls /mnt/stateful_partition/murkmod`? Realistically, I don't expect the system to be able to even boot without this folder existing. Also check startup logs in `/` and try rerunning the updater in mush.

**Comment by Packjackisback** [comment]
Yeah, the folder didn't exist until a updater run. Weird bug.
