### ISSUE TITLE
command exit code 1. "Finding free!!!"

### ISSUE THREAD

**Issue by sites1235** [rainestorme/murkmod#109]
**Describe the bug**
Command failed with exit code 1 Failed to set up loop device: No such file or directory. 

**To Reproduce**
1. Attempt murkmod
2. See error

**Expected behavior**
Murkmod installing

**Screenshots**
![image](https://github.com/user-attachments/assets/72fd9c94-174f-4b4b-b8ae-184f790c2100)

**System (please complete the following information):**
 - octopus
 - v130
- VT2

**Additional context**

**Comment by Packjackisback** [comment]
I'm gonna assume this is related to the fix implemented previously. 

Can you send the output of `losetup -f`?

**Comment by sites1235** [comment]
> I'm gonna assume this is related to the fix implemented previously.
> 
> Can you send the output of `losetup -f`?

FINDING FREE!!!
/dev/loop13

**Comment by Packjackisback** [comment]
hmm. Are you sure you are using the most current version? To make sure everything is working try `losetup -f | tail -1`. It is possible we have forgotten to fix a losetup somewhere, but if you are using a different link than tinyurl.com/murkmod, then please make sure you use that.

**Comment by sites1235** [comment]
> hmm. Are you sure you are using the most current version? To make sure everything is working try `losetup -f | tail -1`. It is possible we have forgotten to fix a losetup somewhere, but if you are using a different link than tinyurl.com/murkmod, then please make sure you use that.

oh i'm using bit.ly/murkmod but the tinyurl link is down.

**Comment by Packjackisback** [comment]
oh yeah, that's what I meant. Can you try running it now?

**Comment by sites1235** [comment]
> oh yeah, that's what I meant. Can you try running it now?

Nope didn't work. Same issue

**Comment by rainestorme** [comment]
In a fork of this repo, there is a workaround that uses the busybox losetup. Perhaps that's the route we should go?

**Comment by sites1235** [comment]
I used KVS to set my kerver to 0 to downgrade to v109 and for some reason it didn't enroll me. Instead I have my school profile with murkmod installed but also my personal account. It didn't even wipe any data

**Comment by sites1235** [comment]
Downgrading to v107 seemed to have fixed the issue as now murkmod works as expected
