### ISSUE TITLE
sed: couldn't write 118 items to /usr/bin/sedUmOhcx: No space left on device

### ISSUE THREAD

**Issue by xytrux** [rainestorme/murkmod#112]
**Describe the bug**
Apparently when updating murkmod, it mentions that there is no space left on a directory that just does not exist.

**To Reproduce**
1. Go to mush
2. Go to 25
3. Error

**Expected behavior**
Updating murkmod

**Screenshots**
If applicable, add screenshots or videos of the problem to help explain your situation.

**System (please complete the following information):**
 - Board trogdor
 - Version 105
- Installation method used fakemurk > murkmod

**Additional context**

**Comment by Packjackisback** [comment]
Are there any other messages before that?

**Comment by Eboi47** [comment]
It would help if you put the full terminal output here, this would help determine the source of the error.

**Comment by xytrux** [comment]
Closing as I had to reinstall everything again (maybe fixed but still cannot update.)

**Comment by xytrux** [comment]
Crazy

**Comment by xytrux** [comment]
```

                      __                      .___
  _____  __ _________|  | __ _____   ____   __| _/
 /     \|  |  \_  __ \  |/ //     \ /  _ \ / __ | 
|  Y Y  \  |  /|  | \/    <|  Y Y  (  <_> ) /_/ | 
|__|_|  /____/ |__|  |__|_ \__|_|  /\____/\____ | 
      \/                  \/     \/            \/

        The fakemurk plugin manager - v6.1.1
Checking for emergency shell...
Installing patched files...
Checking for legacy fakemurk daemon...
Creating stateful partition files...
Patching policy...
Use murkmod reccomended pollen config? [Y/n] y
Setting chronos user password...
New password: Retype new password: passwd: Authentication token manipulation error
passwd: password unchanged
Checking sudo perms...
chronos ALL=(ALL) NOPASSWD: ALL
Looks like sudo permissions are already set correctly.
Setting crossystem cros_debug...
sed: couldn't write 118 items to /usr/bin/sed5OXZjx: No space left on device
cat: /mnt/stateful_partition/fakemurk_version: No such file or directory

Analytics collected.
Done. If cros_debug was enabled for the first time, a reboot may be required. Press any key to exit.
```

**Comment by rainestorme** [comment]
It seems like you unintentionally updated ChromeOS when you meant to update murkmod. As previously stated in other issues, the ChromeOS update feature is unstable and a warning is provided before running it for a reason. Try recovering and reinstalling murkmod by either upgrading fakemurk > murkmod or using the devmode installer directly - see [here](https://github.com/rainestorme/murkmod/blob/main/docs/installation.md).
