### ISSUE TITLE
unable to use crosssystem

### ISSUE THREAD

**Issue by pazza2234** [rainestorme/murkmod#17]
**Describe the bug**

([original issue](https://github.com/eupnea-linux/depthboot-builder/issues/77))

I can not run depth boot because I cant do this, and it is on there (tutorial)[https://eupnea-linux.github.io/docs/depthboot/build-instructions]. Think it is a murk mod or fake murk problem because of ```warning: /mnt/stateful_partition/mwtrollinggoogleforfakemurk:  warning: script from noexec mount``` and in the murk mod setup it tells us to not make issues on fake murk if we have murk mod.

I have a problem, where I can not run this command ```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0``` with out it either giving the error ```/usr/bin/crossystem: line 170: warning: /mnt/stateful_partition/mwtrollinggoogleforfakemurk:  warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md``` or, after I remounted /mnt/stateful_partition with exec, and executed it it looked fine but gave me a error when I pressed ctrl + u that I have not enabled USB boot. 

**To Reproduce**

1. go to Chromebook, open shell and type ```sudo crossystem dev_boot_usb=1 dev_boot_signed_only=0```
2. have it fail, and run ```mount -o remount,exec /mnt/stateful_partition```
3. run step 4 again
4. reboot to the Dev mode screen where you normally press ctrl + d
5. it gives you a error code in the top left of the screen wile the image stays there... and the error code ```warning: booting from external media (USB/SD) has not bin enabled```

**Additional context**
- My Chromebook is the dell 3100, and is on the octopus board.
- I am stupid so I might ask a few dumb questions sorry.
- It is on chrome OS 107.
- Root verification is off.
- I might enable it if it is a solution, but I do not got legacy bios enabled.
- I am not using ctrl + c and ctrl + v to type this, so it may not be 100% accurate but I typed as well as I could. It all looks right. Sorry if I missed type something.

this was originally a issue I made on [depthboot-builder](https://github.com/eupnea-linux/depthboot-builder) but they told me to come here.

**Comment by pazza2234** [comment]
yoooo more context!!!
[Screen recording 2023-05-18 10.17.11 PM.webm](https://github.com/rainestorme/murkmod/assets/81707002/2090b278-3d63-4a6c-922a-a30fa7c81769)

**Comment by pazza2234** [comment]
here is a copy of cross-system thingy. is it broken or something?
[crossystem(copy).txt](https://github.com/rainestorme/murkmod/files/11517403/crossystem.copy.txt)
(also, this is what normally happens with out remounting /mnt/stateful_part)
```
localhost ~ # crossystem dev_usb_boot=1
/usr/bin/crossystem: line 170: warning: /mnt/stateful_partition/mwtrollinggoogleforfakemurk: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
```

**Comment by rainestorme** [comment]
I have some instructions on this exact topic [here](https://chromebook-guide.github.io/depthboot), with modified instructions for fakemurked devices. If that doesn't fix your problem, re-open this issue.

**Comment by rainestorme** [comment]
Also, real-time modification of crossystem values aren't possible. If you want to set a value in crossystem, you'll have to manually run `vi $(which crossystem)` to edit in the values yourself.

**Comment by pazza2234** [comment]
ok. sorry thanks for explaining! sorry for the inconvenience.

**Comment by pazza2234** [comment]
fyi it did not work the way you said. but thats my problom.
