### ISSUE TITLE
Chromebook frozen on boot screen

### ISSUE THREAD

**Issue by clockworkindustries-old-old** [rainestorme/murkmod#19]
Unsure of what causes this.

**Comment by ClockworkIndustries** [comment]
Steps to reproduce:

- Install murkmod
- Install FakeAPK plugin
- Run FakeAPK plugin & enable FakeAPK
- Reboot

Notes: I'm still able to access TTY2 when its stuck on the boot screen.

**Comment by rainestorme** [comment]
Strange. Probably some sort of issue with cros_debug, have you tried booting from a shim/RecoMod to try to set it back to normal?

**Comment by rainestorme** [comment]
Stale, closed. If you're still having issues, please reopen this issue.

**Comment by rainestorme** [comment]
Is it after installing murkmod, or after installing fakemurk? Are you using a compatible version of fakemur

**Comment by rainestorme** [comment]
Closed, stale
