### ISSUE TITLE
Unable to update/install - Read only file system

### ISSUE THREAD

**Issue by DiffuseHyperion** [rainestorme/murkmod#2]
![Screenshot 2023-03-29 11 32 03 AM](https://user-images.githubusercontent.com/95083897/228419834-ebc69f13-71b7-4e35-a269-9225f7626389.png)

Unable to install the murkmod files from murkmod menu.

**Comment by DiffuseHyperion** [comment]
nevermind, its an issue with my chromebook

**Comment by rainestorme** [comment]
Did you end up accidentally re-enabling rootfs verification? If so, you could try powerwashing, the unenrolling and fakemurking again. Then, try to reinstall murkmod.
