### ISSUE TITLE
Collaboration Request

### ISSUE THREAD

**Issue by frantene** [rainestorme/murkmod#26]
Hello, i noticed you dont have any contacts i can look into. Im sending this message in order to ask if you would like to co-operate with my site?
I got inspired by your site called "Goodbye GoGuardian" and i wanted to see if you would like to team up and make the site better and harder for goguardian to block. 
Contact franciscot105152@gmail.com please

**Comment by rainestorme** [comment]
![Screenshot 2023-10-18 11 26 46 AM](https://github.com/rainestorme/murkmod/assets/115757568/3e254c6a-f0a5-4e69-b812-ce09a23cb708)
