### ISSUE TITLE
Installing failure 

### ISSUE THREAD

**Issue by Wildtick** [rainestorme/murkmod#3]
![image](https://user-images.githubusercontent.com/110534522/230687047-a35e2c6c-e0da-4cf2-90cb-f0d29699dc25.png)
When i run the script and open a new crosh tab nothing changes and gives me an error that it's a read-only file system.

**Comment by rainestorme** [comment]
First off: are you sure - 100% sure - that you ran fakemurk before this? And is there a chance that you ran out of storage space? You can't run murkmod directly from an enrolled crosh tab.

**Comment by Wildtick** [comment]
> 
Yes i'm in fakemurk duh...
but i'll look into the storage space
