### ISSUE TITLE
[v118] GAC reporting tests

### ISSUE THREAD

**Issue by rainestorme** [rainestorme/murkmod#33]
We need to test GAC reporting, make sure crossystem.sh hasn't been broken by updates, and otherwise ensure libcrosssystem hasn't been changed significantly since v107.

**Comment by rainestorme** [comment]
> [@rainestorme](https://github.com/rainestorme)
> 
> [MercuryWorkshop/fakemurk#12](https://github.com/MercuryWorkshop/fakemurk/issues/12)
> 
> does this issue still occur w/ murkmod?
> 
> asking becasue my sysadmin took my cb away eventhough it was murkmodded, and no i didn't do any stupid stuff.

Very likely, yes.

**Comment by T3M1N4L** [comment]
@Eboi47 isn't terraos cros js v107 or can it be greater versions like say 125
