### ISSUE TITLE
Plugin Manager Broken

### ISSUE THREAD

**Issue by pazza2234** [rainestorme/murkmod#44]
# The plugin manager is broken for me

## Here is a screen shot

![Screenshot 2023-12-04 8 00 05 AM](https://github.com/rainestorme/murkmod/assets/81707002/270b1966-133b-42db-8b88-9ea9222733cf)

For each entery, it just display's ```(version  by  )``` But not the plug in name. Also if I install, it dose not show up in the plugin runner.

**Comment by rainestorme** [comment]
Have you tried connecting to a different WiFi network? Also, what version of chromeOS are you using?

**Comment by pazza2234** [comment]
I am on V107, And yes I have try'd other networks. Though if I enable my schools extension blocker (go guardian) github's  raw files (https://raw.githubusercontent.com/) is blocked. That is only in browser and I have it disabled right? also I can acsess them. I feal like if this is a router issue, you could add a legacy installer maybe?
![Screenshot 2023-12-05 7 35 47 AM](https://github.com/rainestorme/murkmod/assets/81707002/f37c8dee-229e-445e-98ed-79f9a583ff94)

**Comment by rainestorme** [comment]
Hmm... fascinating. Would you mind opening a root shell and trying to run `jq`?

**Comment by rainestorme** [comment]
Here's a video of what the plugin manager *should* be looking like:

[Screen recording 2023-12-05 10.50.31 AM.webm](https://github.com/rainestorme/murkmod/assets/115757568/d5497b64-4624-45f4-8c86-e5f47981d7d6)

**Comment by rainestorme** [comment]
Closing, stale.
