### ISSUE TITLE
(118/phoenix) find: '/mnt/stateful_partition/murkmod/plugins': No such file or directory 

### ISSUE THREAD

**Issue by yeslol122** [rainestorme/murkmod#65]
find: '/mnt/stateful_partition/murkmod/plugins': No such file or directory is the error I get when I try to install a plugin and the helper says mush is not ready yet (118/grunt treeya/wp disabled/installed with dev mode VT2 command)

**Comment by rainestorme** [comment]
Are you on the latest version of murkmod? Have you tried running an update to create the folder for you? Also attach console output from the helper if you're having issues with it.

**Comment by yeslol122** [comment]
The cb I had that had murkmod broke but whenever im able to install murkmod on this one I will try, thanks
