### ISSUE TITLE
mush is not ready yet

### ISSUE THREAD

**Issue by alexstilldraws** [rainestorme/murkmod#77]
When doing anything with the helper ext, it says "mush is not ready yet"
1. install the helper
2. Click on anything in the helper
3. See error

**Expected behavior**
the extension working

**Screenshots**
![Screenshot 2024-05-26 7 26 35 PM](https://github.com/rainestorme/murkmod/assets/64626447/d54dce62-afc9-4ffa-b0b5-452044d4ec1f)

**System:**
 - Board octopus
 - Version  v118
- Installation method used devmode installer

**Comment by rainestorme** [comment]
First, verify that you're on the latest version of murkmod. Update it with the last option in mush (Ctrl+Alt+T). If that doesn't fix the issue, open the helper and enter the Konami code (Up, up, down, down, left, right, left, right, B, A) - a developer menu will appear at the bottom of the helper. Open it and select "Open xterm". Post the contents of this window here.

**Comment by Eboi47** [comment]
This might be due to the Secure Shell App being now deprecated. It shows that as an error when you go to the manage extensions page for Murkmod helper.

**Comment by Packjackisback** [comment]
Potentially related issue, the crosh window opens for a split second and closes. In the XTerm window it functions as expected, but I also get the error `mush is not ready yet` (Octopus 120)

**Comment by alexstilldraws** [comment]
sorry, i thought i had already made this comment but i eventually fixed it by updating murkmod.
