### ISSUE TITLE
Corrupted

### ISSUE THREAD

**Issue by inLnx** [rainestorme/murkmod#79]
**Describe the bug**
Was on 113. My Chromebook updated itself during install. It corrupted but I had a recovery usb
**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos of the problem to help explain your situation.

**System (please complete the following information):**
 - Board Octopus
 - Version 113-127
- Installation method used - devmode

**Additional context**

**Comment by rainestorme** [comment]
A bit more information is needed to work on this - I can't really tell what happened (and maybe you can't either, and that's fine) - chances are that this was a one-off issue. If it comes up again, take close note of exactly what happens and upload some logs or a video if you can.
