### ISSUE TITLE
Trying to select an option other than "latest" will not work when installing or updating murkmod.

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#82]
**Describe the bug**
Murkmod can only find the latest version of chromeOS. if you select options 1 to 4, or 6, it will result in an error when trying to install that complains about being unable to find the correct version, and it exits the program.

**To Reproduce**
1. Open the devmode terminal using CTRL+ALT+-> OR open mush
2. Login as root OR press 1 for Root Shell and use the command to open the murkmod installer
3. press keys 1, 2, 3, 4, or 6 (you need to select a version if pressing 6) and press enter.
4. answer the bootsplash prompt.
5. Wait a few seconds and see error

**Expected behavior**
It should install murkmod normally and proceed without an error.

**Screenshots**
![image](https://github.com/user-attachments/assets/cdd648d9-edd0-4aba-8008-e98f4f3cc439)

**System (please complete the following information):**
 - Board [Dedede]
 - Version [v117 & v128] (tested w both)
- Installation method used [devmode installer]

**Additional context**
-It works perfectly fine if you press 5 and use the latest version. 
-All selectable versions are on chrome100.dev

**Comment by rainestorme** [comment]
Looks like Chrome100 changed how it stores stuff... I'll push a patch in a few minutes.

**Comment by rainestorme** [comment]
Bit more than a few minutes... but it seems to work now.
