### ISSUE TITLE
Devmode installer breaks in the middle of installation

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#83]
**Describe the bug**
When using the devmode installer, midway through installation, there will be an error,  and the program will end.
**To Reproduce**
1. Put Chromebook into dev mode and connect to wifi
2. Press CTRL+ALT+ -> to open terminal
3. Log in as root and run the installer command 
4. Select any version
5. Press any key and enter
6. Wait a while depending on the version selected
7. See error

**Expected behavior**
Murkmod should install correctly without error

**Screenshots**
One of these errors will show up:
![PXL_20240914_235704131 LONG_EXPOSURE-01 COVER](https://github.com/user-attachments/assets/45a67fa0-b95f-467c-829c-fcb456721a45)
![PXL_20240915_000529926](https://github.com/user-attachments/assets/9f2d0d1b-af64-4df3-a065-58ab5acf697c)

**System (please complete the following information):**
 - Board [Dedede]
 - Version [v117]
- Installation method used [devmode installer]

**Additional context**
-this could be related to the recent update that fixed being unable to find the version selected.
-I tested this with all versions but v118 (chrome100 does not have v118 for my board).

**Comment by rainestorme** [comment]
Okay, this looks like 2 completely seperate issues - in the first one, it's got to be an issue with the new `get_largest_cros_blockdev` routine, but I'm frankly at a loss for the second error - I can't read that fully, nor does it seem like a valid error. Did you reboot between the two runs of the installer? If not, that's probably the cause of the second one.

**Comment by rainestorme** [comment]
Although this issue is closed, feel free to reopen it if this patch doesn't fix the issue.

**Comment by Eboi47** [comment]
I didn't reboot in between runs, so that is likely the cause of the second error.
