### ISSUE TITLE
Plugins don't show up in mush.

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#85]
**Describe the bug**
When using mush, pressing 4 will not show any plugins, but it will show an error. This error complains about a file not being found.

**To Reproduce**
1. Press CTRL + ALT + T simultaneously to open mush
2. Press 4 and then ENTER

**Expected behavior**
The plugin menu should appear as normal.

**Screenshots**
![image](https://github.com/user-attachments/assets/87daa51c-4272-43a9-b46b-7d0c483bc04a)

**System (please complete the following information):**
 - Board [Dedede]
 - Version [v119]
- Installation method used [devmode installer]

**Additional context**
-You can still install plugins, but trying to load or uninstall them will result in an error.

**Comment by rainestorme** [comment]
Alright... try running the update function from mush and see if that fixes the problem.

**Comment by Eboi47** [comment]
The plugins show up again!

**Comment by rainestorme** [comment]
This should work out of the box without needing to update, so it is a bug

**Comment by rainestorme** [comment]
I'll close this as invalid for now just because this is an easily fixed issue and I don't really want to implement a whole additional mechanism for modifying the stateful partition on the first boot of a newly installed system.
