### ISSUE TITLE
Selecting version 117 will not work

### ISSUE THREAD

**Issue by Eboi47** [rainestorme/murkmod#86]
**Describe the bug**
If you select a version of murkmod that matches the version currently on your Chromebook, it will not work.

**To Reproduce**
1. Go to the terminal with CTRL + ALT + ->
2. Log in as root
3. Use the Devmode installer command
4. Select version 117
5. Press Y or N and then ENTER
6. Wait and see error

**Expected behavior**
Murkmod should have installed correctly.

**Screenshots**
![PXL_20240919_223112883](https://github.com/user-attachments/assets/ce93aa2b-7f9b-4990-8e6c-04db29ed472e)

**System (please complete the following information):**
 - Board [Dedede]
 - Version [v117]
- Installation method used [devmode installer]

**Additional context**
-Using any other Murkmod version works just fine
-this may be linked to having v117 as the OS version before installing.

**Comment by rainestorme** [comment]
I have absolutely no idea why this isn't working. If you can record a video of the earlier output, or interrupt the process (with <kbd>Ctrl+C</kbd>) right after it searches Chrome100 and post an image of the logs, that would be greatly appreciated. Maybe I should add a mechanism to export the logs from the installer...

**Comment by Ogyeet10** [comment]
Same issue and same errors. 107 works, I'm just using that.

**Comment by rainestorme** [comment]
Should be fixed.
