### ISSUE TITLE
dev_install is broken

### ISSUE THREAD

**Issue by SlideShowGames** [rainestorme/murkmod#95]
Probably not a murkmod problem but still, I’m on octopus, I used sh1mmer, I’m on 105. It might be because of my version but idk.
![IMG_2740](https://github.com/user-attachments/assets/4047e399-8734-42f4-9f64-dd2224239ad0)

**Comment by Eboi47** [comment]
I"m no expert, but it could be your version, update to a later version or restart the chromebook, and try again. Provide more information as well, such as how to replicate the error.

**Comment by rainestorme** [comment]
Yes - it's definitely because of your version. Google's portage servers are only keeping builds for a few recent builds of the OS for each board - you'd need to update to a newer version to use the devmode installer.
