### ISSUE TITLE
Murkmod install bricks

### ISSUE THREAD

**Issue by Wildtick** [rainestorme/murkmod#99]
**Describe the bug**
Every time I try to install murkmod after the setup reboots it shows up with the "chromeos is missing or damaged" and I'm forced to recover using a USB

**To Reproduce**
1. Install murkmod on 121
2. use 121 for install version
3. Wait for it to finish
4. Reboot
5. Error

**Expected behavior**
I shouldn't get this at all

**Screenshots**
I'm too lazy to go through the script again

**System (please complete the following information):**
 - Board: Octopus
 - Version: 121
- Installation method used: devmode installer

**Additional context**
The only reason i'm doing 121 is because i have device minimum version and it's set to 120; so, 120 isn't in chrome100.dev so the script can't find the recovery image.

**Comment by Wildtick** [comment]
![IMG_20241103_132754](https://github.com/user-attachments/assets/5285f6bf-a8ca-4787-87e0-daa6db3d8300)
![1730662177958151357497487480200](https://github.com/user-attachments/assets/d77d9b60-bbe4-4035-92fc-8c3dd00e2098)
I took these to maybe help

**Comment by Packjackisback** [comment]
I have the same issue

**Comment by Wildtick** [comment]
Make sure not to sign in when running the script
connect to wifi in the bottom right corner
